from location_ids import Location

OBJECT_DEFS = [
    # --- Cell objects ---
    {
        "id": "puzzle_piece_1",
        "name": "puzzle piece 1",
        "location": Location.CELL_1,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "puzzle piece 1",
    },
    {
        "id": "hint1",
        "name": "hint 1",
        "location": Location.CELL_1,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "hint #1",
    },
    {
        "id": "clue1",
        "name": "clue 1",
        "location": Location.CELL_2,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "clue #1",
    },
    {
        "id": "clue11",
        "name": "clue 1-2",
        "location": Location.CELL_1,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "clue #1.5",
    },
    {
        "id": "clue2",
        "name": "clue 2",
        "location": Location.CELL_3,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "clue #2 (ONLY READ ONCE HINT 1 IS SOLVED)",
    },
    {
        "id": "puzzle",
        "name": "puzzle",
        "location": Location.CELL_3,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "puzzle",
    },
    {
        "id": "puzzle_1",
        "name": "puzzle (1/4)",
        "location": "puzzle",
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "puzzle",
    },
    {
        "id": "puzzle_2",
        "name": "puzzle (2/4)",
        "location": "puzzle_1",
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "puzzle",
    },

    # --- Vault ---
    {
        "id": "scroll",
        "name": "scroll",
        "location": Location.CELL_1,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "an ancient papyrus scroll",
    },
    {
        "id": "scroll_hint",
        "name": "hint",
        "location": Location.VAULT_4,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "huh",
    },
    {
        "id": "safe",
        "name": "safe",
        "location": Location.VAULT_3,
        "movable": False,
        "visible": True,
        "carried": False,
        "description": "a small safe",
    },
    {
        "id": "gold_bar",
        "name": "gold bar",
        "location": Location.VAULT_4,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "a gold bar with an engraving in it",
    },
    {
        "id": "bar_clue",
        "name": "clue",
        "location": Location.VAULT_4,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "clue",
    },
    {
        "id": "puzzle_piece_2",
        "name": "puzzle piece 2",
        "location": Location.VAULT_3,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "puzzle piece 2",
    },

    # --- Hallway hint fragments ---
    *[
        {
            "id": f"hint_fragment_{i}",
            "name": f"hint {chr(64+i)}",
            "location": getattr(Location, f"HALLWAY_{i}"),
            "movable": True,
            "visible": i == 1,
            "carried": False,
            "description": "a small piece of ripped paper, it looks like it has some writing on it.",
            "glueable": True,
        }
        for i in range(1, 14)
    ],

    {
        "id": "fragment_clue",
        "name": "cluee",
        "location": Location.HALLWAY_13,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "more ripped looking paper...",
    },

    {
        "id": "puzzle_piece_3",
        "name": "puzzle piece 3",
        "location": Location.HALLWAY_10,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "another puzzle piece woo",
    },

    {
        "id": "puzzle_3",
        "name": "puzzle (3/4)",
        "location": "puzzle_2",
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "puzzle (3/4)",
    },

    # --- Supply rooms ---
    {
        "id": "glue_stick",
        "name": "glue stick",
        "location": Location.SUPPLY_1,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "a glue stick",
    },
    {
        "id": "hint3",
        "name": "hint 3",
        "location": None,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "hint 3",
    },
    {
        "id": "door",
        "name": "door",
        "location": Location.HALLWAY_13,
        "movable": False,
        "visible": True,
        "carried": False,
        "description": "a large door...",
    },
    {
        "id": "finished_puzzle",
        "name": "puzzle (4/4)",
        "location": "puzzle_3",
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "a finished puzzle, what does it do?",
    },
    {
        "id": "puzzle_piece_4",
        "name": "puzzle piece 4",
        "location": Location.SUPPLY_2,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "another puzzle piece...",
    },
    {
        "id": "key",
        "name": "key",
        "location": "finished_puzzle",
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "a golden key",
    },
    {
        "id": "magnifying_glass",
        "name": "magnifying glass",
        "location": Location.HALLWAY_13,
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "a magnifying glass",
    },
    {
        "id": "broom",
        "name": "broom",
        "location": Location.SUPPLY_2,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "a broom",
    },
    {
        "id": "bucket",
        "name": "bucket",
        "location": Location.SUPPLY_2,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "an empty bucket",
    },
    {
        "id": "bucket_filled",
        "name": "water bucket",
        "location": "bucket",
        "movable": True,
        "visible": False,
        "carried": False,
        "description": "a bucket filled with water",
    },
    {
        "id": "trapdoor",
        "name": "trapdoor",
        "location": Location.HALLWAY_10,
        "movable": False,
        "visible": False,
        "carried": False,
        "description": "a trapdoor",
    },
    {
        "id": "water",
        "name": "water",
        "location": Location.SUPPLY_2,
        "movable": False,
        "visible": True,
        "carried": False,
        "description": "water",
    },
    {
        "id": "lighter",
        "name": "lighter",
        "location": Location.SUPPLY_2,
        "movable": True,
        "visible": True,
        "carried": False,
        "description": "a lighter, maybe you could light a fire with this?",
    },
]
